/**
 * Core Schema and Data for Human Diseases
 * Includes Genetic, Infectious, Metabolic, Autoimmune, and Rare Diseases.
 */

export interface DiseaseInfo {
    id: string;
    name: { en: string; hi: string };
    type: 'genetic' | 'infectious' | 'metabolic' | 'autoimmune' | 'nutritional' | 'rare' | 'neurodegenerative' | 'communicable' | 'injury' | 'venomous_bite' | 'mental_health' | 'neurological' | 'gynaecological' | 'sti';
    causes: string[];
    riskFactors: string[];
    symptoms: string[];
    progression: string;
    diagnosticMarkers: string[];
    prevention: string;
    treatmentOptions: string[];
    requiresExpert: boolean;
    genomicLinks?: string[];
}

export const DISEASE_MODEL: Record<string, DiseaseInfo> = {
    'fop': {
        id: 'fop',
        name: { en: 'Fibrodysplasia Ossificans Progressiva', hi: 'फाइब्रोडिस्प्लाशिया ऑसिफ़िकन्स प्रोग्रेसिव' },
        type: 'rare',
        causes: ['Mutation in the ACVR1 gene'],
        riskFactors: ['Genetic inheritance (autosomal dominant)'],
        symptoms: ['Heterotopic ossification (bone forming in muscles)', 'Malformed big toes at birth'],
        progression: 'Episodes of painful soft tissue swelling followed by bone formation, leading to progressive loss of mobility.',
        diagnosticMarkers: ['Clinical examination of big toes', 'Genetic testing for ACVR1 mutation'],
        prevention: 'Avoidance of intramuscular injections and physical trauma.',
        treatmentOptions: ['Symptomatic relief', 'Corticosteroids during flare-ups', 'Palovarotene (FDA approved)'],
        requiresExpert: true,
        genomicLinks: ['ACVR1 gene mutation']
    },
    'huntingtons': {
        id: 'huntingtons',
        name: { en: 'Huntington\'s Disease', hi: 'हंटिंगटन रोग' },
        type: 'neurodegenerative',
        causes: ['Genetic mutation in the HTT gene (CAG repeats)'],
        riskFactors: ['Family history', 'CAG repeat length'],
        symptoms: ['Involuntary movements (chorea)', 'Cognitive decline', 'Psychiatric issues'],
        progression: 'Progressive loss of brain function over 10-30 years.',
        diagnosticMarkers: ['Genetic testing (36+ CAG repeats)', 'Brain imaging (MRI)'],
        prevention: 'None known.',
        treatmentOptions: ['Management of symptoms (tetrabenazine)', 'Physical therapy'],
        requiresExpert: true,
        genomicLinks: ['HTT gene on chromosome 4']
    },
    'lupus': {
        id: 'lupus',
        name: { en: 'Systemic Lupus Erythematosus (SLE)', hi: 'सिस्टमिक ल्यूपस एरिथोमेटोसस' },
        type: 'autoimmune',
        causes: ['Combination of genetics', 'Hormones', 'Environment'],
        riskFactors: ['Female sex (15-45 age)', 'Family history', 'UV exposure'],
        symptoms: ['Butterfly rash', 'Joint pain', 'Fatigue', 'Kidney issues'],
        progression: 'Periods of flares and remission, potential organ damage.',
        diagnosticMarkers: ['Positive ANA test', 'Anti-dsDNA antibodies', 'ESR/CRP levels'],
        prevention: 'Avoid UV light, manage stress.',
        treatmentOptions: ['Hydroxychloroquine', 'Corticosteroids', 'Immunosuppressants'],
        requiresExpert: true,
        genomicLinks: ['HLA-DRB1 and over 180 other genetic variants']
    },
    'covid-19': {
        id: 'covid-19',
        name: { en: 'COVID-19', hi: 'कोविड-19' },
        type: 'communicable',
        causes: ['SARS-CoV-2 virus'],
        riskFactors: ['Elderly age', 'Underlying health conditions', 'Close contact'],
        symptoms: ['Fever', 'Cough', 'Shortness of breath', 'Loss of taste/smell'],
        progression: 'From mild symptoms to severe pneumonia or Long COVID.',
        diagnosticMarkers: ['PCR test', 'Rapid antigen test'],
        prevention: 'Vaccination, masks, hand hygiene.',
        treatmentOptions: ['Symptomatic relief', 'Antiviral medications', 'Oxygen therapy'],
        requiresExpert: true
    },
    'malaria': {
        id: 'malaria',
        name: { en: 'Malaria', hi: 'मलेरिया' },
        type: 'communicable',
        causes: ['Plasmodium parasite via Anopheles mosquito'],
        riskFactors: ['Stagnant water', 'No mosquito nets', 'Tropical regions'],
        symptoms: ['High fever', 'Chills', 'Sweating', 'Headache'],
        progression: 'Cyclical fever paroxysms; can lead to organ failure.',
        diagnosticMarkers: ['Blood smear microscopy', 'Rapid diagnostic test (RDT)'],
        prevention: 'Mosquito nets, repellents, preventive drugs.',
        treatmentOptions: ['Artemisinin-based combination therapy (ACT)', 'Chloroquine'],
        requiresExpert: true
    },
    'diabetes-t2': {
        id: 'diabetes-t2',
        name: { en: 'Type 2 Diabetes', hi: 'टाइप 2 मधुमेह' },
        type: 'metabolic',
        causes: ['Insulin resistance', 'Genetic predisposition'],
        riskFactors: ['Obesity', 'Physical inactivity', 'Family history'],
        symptoms: ['Increased thirst', 'Frequent urination', 'Fatigue', 'Blurred vision'],
        progression: 'Can lead to heart disease, kidney failure, and nerve damage.',
        diagnosticMarkers: ['HbA1c test', 'Fasting blood glucose test'],
        prevention: 'Healthy diet, regular exercise, weight management.',
        treatmentOptions: ['Metformin', 'Insulin therapy', 'Lifestyle changes'],
        requiresExpert: true
    },
    'snake-bite': {
        id: 'snake-bite',
        name: { en: 'Venomous Snake Bite', hi: 'जहरीला सांप का काटना' },
        type: 'venomous_bite',
        causes: ['Venom injection from cobra, krait, viper, etc.'],
        riskFactors: ['Walking in tall grass', 'Handling snakes'],
        symptoms: ['Severe pain', 'Swelling', 'Difficulty breathing', 'Gums bleeding'],
        progression: 'Rapid tissue damage or systemic paralysis/clotting issues.',
        diagnosticMarkers: ['Fang marks', 'Blood coagulation tests'],
        prevention: 'Boots in grass, avoid handling snakes.',
        treatmentOptions: ['Anti-venom serum (AVS)', 'Immobilization', 'Wound care'],
        requiresExpert: true
    },
    'fracture': {
        id: 'fracture',
        name: { en: 'Bone Fracture (Broken Bone)', hi: 'हड्डी टूटना (फ्रैक्चर)' },
        type: 'injury',
        causes: ['High-impact trauma', 'Falls', 'Stress'],
        riskFactors: ['Osteoporosis', 'Contact sports'],
        symptoms: ['Deformity', 'Intense pain', 'Swelling', 'Inability to move'],
        progression: 'Hematoma formation followed by bone remodeling.',
        diagnosticMarkers: ['X-ray', 'CT scan'],
        prevention: 'Nutrient-rich diet (calcium/Vit D), safety gear.',
        treatmentOptions: ['Casting', 'Splinting', 'Surgery (ORIF)'],
        requiresExpert: true
    },
    'bipolar': {
        id: 'bipolar',
        name: { en: 'Bipolar Disorder', hi: 'बाइपोलर डिसऑर्डर' },
        type: 'mental_health',
        causes: ['Brain chemistry imbalance', 'Genetic factors'],
        riskFactors: ['High stress', 'Family history'],
        symptoms: ['Manic episodes (high energy)', 'Depressive episodes (low mood)'],
        progression: 'Cyclical mood swings varying in frequency.',
        diagnosticMarkers: ['Psychiatric evaluation (DSM-5)'],
        prevention: 'Stress management, early intervention.',
        treatmentOptions: ['Mood stabilizers', 'Psychotherapy', 'Antipsychotics'],
        requiresExpert: true
    },
    'alzheimers': {
        id: 'alzheimers',
        name: { en: 'Alzheimer\'s Disease', hi: 'अल्जाइमर रोग' },
        type: 'neurological',
        causes: ['Amyloid plaques and Tau tangles in brain'],
        riskFactors: ['Ageing', 'Genetics', 'Head injuries'],
        symptoms: ['Memory loss', 'Confusion', 'Difficulty with daily tasks'],
        progression: 'Gradual decline of cognitive and physical function.',
        diagnosticMarkers: ['Neuropsychological tests', 'Brain MRI/PET scan'],
        prevention: 'Mental stimulation, healthy diet.',
        treatmentOptions: ['Cholinesterase inhibitors', 'Memantine'],
        requiresExpert: true
    },
    'tuberculosis': {
        id: 'tuberculosis',
        name: { en: 'Tuberculosis (TB)', hi: 'तपेदिक (टीबी)' },
        type: 'communicable',
        causes: ['Mycobacterium tuberculosis bacteria'],
        riskFactors: ['Weak immune system', 'Crowded living conditions'],
        symptoms: ['Persistent cough (>3 weeks)', 'Coughing blood', 'Night sweats'],
        progression: 'Can damage lungs and spread to other organs if untreated.',
        diagnosticMarkers: ['Sputum test', 'Chest X-ray', 'Mantoux test'],
        prevention: 'BCG vaccine, respiratory hygiene.',
        treatmentOptions: ['Long-term antibiotics (DOTS)'],
        requiresExpert: true
    },
    'hypertension': {
        id: 'hypertension',
        name: { en: 'Hypertension (High BP)', hi: 'उच्च रक्तचाप (हाई बीपी)' },
        type: 'metabolic',
        causes: ['High salt intake', 'Stress', 'Genetics'],
        riskFactors: ['Ageing', 'Obesity', 'Sedentary lifestyle'],
        symptoms: ['Headache', 'Dizziness', 'Vision changes', 'Chest pain'],
        progression: 'Increases risk of stroke, heart attack, and kidney disease.',
        diagnosticMarkers: ['Blood pressure measurement (>140/90 mmHg)'],
        prevention: 'Low salt diet, exercise, stress management.',
        treatmentOptions: ['Antihypertensive medications', 'Lifestyle changes'],
        requiresExpert: true
    },
    'depression': {
        id: 'depression',
        name: { en: 'Major Depressive Disorder', hi: 'अवसाद (डिप्रेशन)' },
        type: 'mental_health',
        causes: ['Biological, environmental, and genetic factors'],
        riskFactors: ['Family history', 'Traumatic events'],
        symptoms: ['Persistent sadness', 'Loss of interest', 'Changes in appetite'],
        progression: 'Can lead to significant functional impairment and self-harm risk.',
        diagnosticMarkers: ['Clinical psychiatric evaluation'],
        prevention: 'Mental health support, stress reduction.',
        treatmentOptions: ['Antidepressants', 'CBT Therapy', 'Lifestyle changes'],
        requiresExpert: true
    },
    'stroke': {
        id: 'stroke',
        name: { en: 'Stroke', hi: 'स्ट्रोक (मस्तिष्क का दौरा)' },
        type: 'neurological',
        causes: ['Blood clot or burst blood vessel in brain'],
        riskFactors: ['Hypertension', 'Smoking', 'High cholesterol'],
        symptoms: ['Face drooping', 'Arm weakness', 'Speech difficulty'],
        progression: 'Rapid death of brain cells; can lead to permanent disability.',
        diagnosticMarkers: ['CT/MRI Scan of brain'],
        prevention: 'BP control, healthy diet, no smoking.',
        treatmentOptions: ['Thrombolysis (clot-busting)', 'Rehabilitation'],
        requiresExpert: true
    },
    'pcos': {
        id: 'pcos',
        name: { en: 'Polycystic Ovary Syndrome (PCOS)', hi: 'पॉलीसिस्टिक ओवरी सिंड्रोम (PCOS)' },
        type: 'gynaecological',
        causes: ['Hormonal imbalance', 'Insulin resistance'],
        riskFactors: ['Obesity', 'Family history'],
        symptoms: ['Irregular periods', 'Excess hair growth', 'Acne', 'Weight gain'],
        progression: 'Can lead to infertility, type 2 diabetes, and heart problems if not managed.',
        diagnosticMarkers: ['Ultrasound (ovarian cysts)', 'Blood tests (androgen levels)'],
        prevention: 'Healthy weight, balanced diet.',
        treatmentOptions: ['Lifestyle changes', 'Birth control pills', 'Metformin'],
        requiresExpert: true
    },
    'endometriosis': {
        id: 'endometriosis',
        name: { en: 'Endometriosis', hi: 'एंडोमेट्रियोसिस' },
        type: 'gynaecological',
        causes: ['Endometrial tissue growing outside the uterus'],
        riskFactors: ['Family history', 'Never giving birth', 'Short menstrual cycles'],
        symptoms: ['Severe pelvic pain', 'Painful periods', 'Pain during intercourse'],
        progression: 'Chronic pain and potential infertility due to adhesions.',
        diagnosticMarkers: ['Laparoscopy', 'Pelvic ultrasound'],
        prevention: 'None specific; early diagnosis is key.',
        treatmentOptions: ['Pain medication', 'Hormone therapy', 'Surgery'],
        requiresExpert: true
    },
    'uterine-fibroids': {
        id: 'uterine-fibroids',
        name: { en: 'Uterine Fibroids', hi: 'गर्भाशय फाइब्रॉएड' },
        type: 'gynaecological',
        causes: ['Noncancerous growths of the uterus'],
        riskFactors: ['Age (30-40s)', 'Obesity', 'Family history'],
        symptoms: ['Heavy menstrual bleeding', 'Long periods', 'Pelvic pressure'],
        progression: 'Can grow in size causing discomfort and anemia from blood loss.',
        diagnosticMarkers: ['Pelvic exam', 'Ultrasound'],
        prevention: 'Maintaining healthy weight.',
        treatmentOptions: ['Watchful waiting', 'Medications', 'Surgery (Myomectomy/Hysterectomy)'],
        requiresExpert: true
    },
    'hiv-aids': {
        id: 'hiv-aids',
        name: { en: 'HIV/AIDS', hi: 'एचआईवी/एड्स' },
        type: 'sti',
        causes: ['Human Immunodeficiency Virus (HIV)'],
        riskFactors: ['Unprotected sex', 'Sharing needles', 'Mother-to-child transmission'],
        symptoms: ['Flu-like symptoms (initial)', 'Weight loss', 'Recurrent infections', 'Fatigue'],
        progression: 'Destroys CD4 cells weakening the immune system; leads to AIDS if untreated.',
        diagnosticMarkers: ['HIV antibody/antigen tests', 'CD4 count', 'Viral load'],
        prevention: 'PrEP, condoms, sterile needles.',
        treatmentOptions: ['Antiretroviral therapy (ART)'],
        requiresExpert: true
    },
    'syphilis': {
        id: 'syphilis',
        name: { en: 'Syphilis', hi: 'सिफलिस' },
        type: 'sti',
        causes: ['Treponema pallidum bacteria'],
        riskFactors: ['Unprotected sex', 'Multiple partners'],
        symptoms: ['Painless sores (chancre)', 'Rash on palms/soles', 'Fever', 'Swollen nodes'],
        progression: 'Primary, secondary, latent, and tertiary stages; can damage heart and brain.',
        diagnosticMarkers: ['RPR/VDRL blood tests', 'Darkfield microscopy'],
        prevention: 'Condoms, safe sex practices.',
        treatmentOptions: ['Penicillin (antibiotics)'],
        requiresExpert: true
    },
    'preeclampsia': {
        id: 'preeclampsia',
        name: { en: 'Preeclampsia', hi: 'प्री-एक्लेम्पसिया' },
        type: 'gynaecological',
        causes: ['High blood pressure during pregnancy'],
        riskFactors: ['First pregnancy', 'History of hypertension', 'Obesity', 'Age >35'],
        symptoms: ['High BP', 'Protein in urine', 'Swelling in hands/face', 'Severe headache'],
        progression: 'Can lead to eclampsia (seizures) and organ failure for mother and baby.',
        diagnosticMarkers: ['Blood pressure (>140/90)', 'Urine protein test'],
        prevention: 'Regular prenatal care, low-dose aspirin (if high risk).',
        treatmentOptions: ['Blood pressure meds', 'Delivery of the baby', 'Magnesium sulfate'],
        requiresExpert: true
    },
    'uterine-prolapse': {
        id: 'uterine-prolapse',
        name: { en: 'Uterine Prolapse', hi: 'गर्भाशय भ्रंश (Uterine Prolapse)' },
        type: 'gynaecological',
        causes: ['Weakened pelvic floor muscles and ligaments'],
        riskFactors: ['Pregnancy', 'Vaginal childbirth', 'Aging', 'Obesity'],
        symptoms: ['Sensation of heaviness', 'Tissue protruding from vagina', 'Urinary issues', 'Pelvic pressure'],
        progression: 'Uterus slips into or protrudes out of the vagina; can lead to ulcers and discomfort.',
        diagnosticMarkers: ['Pelvic exam'],
        prevention: 'Kegel exercises, weight management.',
        treatmentOptions: ['Pessary (support device)', 'Pelvic floor therapy', 'Surgery'],
        requiresExpert: true
    },
    'ovarian-cyst': {
        id: 'ovarian-cyst',
        name: { en: 'Ovarian Cyst', hi: 'अंडाशय की पुटी (Ovarian Cyst)' },
        type: 'gynaecological',
        causes: ['Normal menstrual cycle (functional)', 'Endometriosis', 'PCOS'],
        riskFactors: ['Hormonal problems', 'Pregnancy', 'Previous cysts'],
        symptoms: ['Pelvic pain', 'Bloat', 'Pressure in abdomen', 'Irregular periods'],
        progression: 'Most cysts disappear; some may rupture causing severe pain or torsion.',
        diagnosticMarkers: ['Ultrasound', 'CA-125 blood test'],
        prevention: 'Regular pelvic exams.',
        treatmentOptions: ['Watchful waiting', 'Birth control', 'Surgery (Cystectomy)'],
        requiresExpert: true
    },
    'ectopic-pregnancy': {
        id: 'ectopic-pregnancy',
        name: { en: 'Ectopic Pregnancy', hi: 'अस्थानिक गर्भावस्था (Ectopic Pregnancy)' },
        type: 'gynaecological',
        causes: ['Fertilized egg implants outside the uterus (usually fallopian tube)'],
        riskFactors: ['Previous ectopic pregnancy', 'History of PID', 'Smoking'],
        symptoms: ['Sharp pelvic pain', 'Vaginal bleeding', 'Shoulder pain', 'Dizziness'],
        progression: 'Life-threatening if the tube ruptures; internal bleeding.',
        diagnosticMarkers: ['hCG levels blood test', 'Transvaginal ultrasound'],
        prevention: 'Safe sex practices to prevent PID.',
        treatmentOptions: ['Methotrexate (medication)', 'Laparoscopic surgery'],
        requiresExpert: true
    },
    'gonorrhea': {
        id: 'gonorrhea',
        name: { en: 'Gonorrhea', hi: 'सुजाक (Gonorrhea)' },
        type: 'sti',
        causes: ['Neisseria gonorrhoeae bacteria'],
        riskFactors: ['Unprotected sex', 'New or multiple partners'],
        symptoms: ['Painful urination', 'Abnormal discharge', 'Pelvic pain'],
        progression: 'Can spread to the uterus and fallopian tubes causing PID and infertility.',
        diagnosticMarkers: ['Urine test', 'Swab of affected area (NAAT)'],
        prevention: 'Condoms, regular screening.',
        treatmentOptions: ['Ceftriaxone (injection antibiotic)'],
        requiresExpert: true
    },
    'chlamydia': {
        id: 'chlamydia',
        name: { en: 'Chlamydia', hi: 'क्लैमिडिया (Chlamydia)' },
        type: 'sti',
        causes: ['Chlamydia trachomatis bacteria'],
        riskFactors: ['Unprotected sex', 'Young age'],
        symptoms: ['Often silent', 'Painful urination', 'Disharge', 'Spotting between periods'],
        progression: 'Common cause of PID and ectopic pregnancy if untreated.',
        diagnosticMarkers: ['Urine test', 'Vaginal swab (NAAT)'],
        prevention: 'Condoms, annual screening.',
        treatmentOptions: ['Azithromycin or Doxycycline (antibiotics)'],
        requiresExpert: true
    },
    'hpv': {
        id: 'hpv',
        name: { en: 'Human Papillomavirus (HPV)', hi: 'एचपीवी (HPV)' },
        type: 'sti',
        causes: ['Human Papillomavirus infection'],
        riskFactors: ['Early sexual activity', 'Multiple partners', 'Weakened immune system'],
        symptoms: ['Genital warts', 'Usually asymptomatic (until cancer screenings)'],
        progression: 'Certain strains cause cervical, anal, and throat cancers.',
        diagnosticMarkers: ['Pap smear test', 'HPV DNA test'],
        prevention: 'HPV Vaccine (Gardasil), condoms.',
        treatmentOptions: ['Topical wart treatments', 'Procedures for precancerous cells (LEEP)'],
        requiresExpert: true
    },
    'gestational-diabetes': {
        id: 'gestational-diabetes',
        name: { en: 'Gestational Diabetes', hi: 'गर्भावस्था मधुमेह (Gestational Diabetes)' },
        type: 'metabolic',
        causes: ['Hormones from the placenta preventing insulin use'],
        riskFactors: ['Obesity', 'Previous gestational diabetes', 'Family history', 'Age >25'],
        symptoms: ['Usually asymptomatic', 'Excessive thirst', 'Frequent urination'],
        progression: 'Can lead to high birth weight, preterm birth, and increased risk of type 2 diabetes later.',
        diagnosticMarkers: ['Glucose challenge test', 'Glucose tolerance test'],
        prevention: 'Healthy diet, regular activity.',
        treatmentOptions: ['Blood sugar monitoring', 'Healthy diet', 'Insulin (if needed)'],
        requiresExpert: true
    },
    'menopause': {
        id: 'menopause',
        name: { en: 'Menopause', hi: 'रजोनिवृत्ति (Menopause)' },
        type: 'gynaecological',
        causes: ['Natural decline in reproductive hormones'],
        riskFactors: ['Aging (usually 45-55)'],
        symptoms: ['Hot flashes', 'Night sweats', 'Irregular periods', 'Vaginal dryness', 'Mood changes'],
        progression: 'The end of menstrual cycles; increased risk of osteoporosis and heart disease.',
        diagnosticMarkers: ['Clinical assessment of symptoms', 'FSH/LH levels blood test'],
        prevention: 'Healthy lifestyle, calcium intake.',
        treatmentOptions: ['Hormone replacement therapy (HRT)', 'Vaginal lubricants', 'Lifestyle changes'],
        requiresExpert: true
    },
    'herpes-genital': {
        id: 'herpes-genital',
        name: { en: 'Genital Herpes', hi: 'जननांग हर्पीस (Genital Herpes)' },
        type: 'sti',
        causes: ['Herpes Simplex Virus (HSV-1 or HSV-2)'],
        riskFactors: ['Unprotected sex', 'Multiple partners'],
        symptoms: ['Sores or blisters in genital area', 'Itching', 'Painful urination', 'Flu-like symptoms'],
        progression: 'Recurrent outbreaks; can be transmitted even when no sores are visible.',
        diagnosticMarkers: ['Viral culture swab', 'PCR test', 'Blood antibody test'],
        prevention: 'Condoms (reduce risk), avoiding sex during outbreaks.',
        treatmentOptions: ['Antiviral medications (Acyclovir/Valacyclovir)'],
        requiresExpert: true
    },
    'trichomoniasis': {
        id: 'trichomoniasis',
        name: { en: 'Trichomoniasis', hi: 'ट्राइकोमोनिएसिस (Trichomoniasis)' },
        causes: ['Trichomonas vaginalis parasite'],
        type: 'sti',
        riskFactors: ['Unprotected sex', 'Multiple partners'],
        symptoms: ['Foul-smelling vaginal discharge (green/yellow)', 'Genital itching', 'Pain during urination'],
        progression: 'Can increase risk of other STIs and cause preterm birth in pregnant women.',
        diagnosticMarkers: ['Microscopic exam of discharge', 'NAAT test'],
        prevention: 'Condoms, safe sex practices.',
        treatmentOptions: ['Metronidazole or Tinidazole (antibiotics)'],
        requiresExpert: true
    },
    'neuropathy': {
        id: 'neuropathy',
        name: { en: 'Peripheral Neuropathy', hi: 'पेरिफेरल न्यूरोपैथी' },
        type: 'neurological',
        causes: ['Diabetes', 'Nerve damage', 'Vitamin deficiencies'],
        riskFactors: ['Diabetes', 'Alcoholism', 'Autoimmune diseases'],
        symptoms: ['Numbness', 'Tingling', 'Muscle weakness', 'Twitching', 'Sharp pain'],
        progression: 'Can lead to loss of sensation and coordination if untreated.',
        diagnosticMarkers: ['EMG (Electromyography)', 'Nerve conduction studies'],
        prevention: 'Blood sugar control, healthy diet.',
        treatmentOptions: ['Pain relievers', 'Anti-seizure medications', 'Physical therapy'],
        requiresExpert: true
    },
    'bfs': {
        id: 'bfs',
        name: { en: 'Benign Fasciculation Syndrome', hi: 'बिनाइन फासीक्यूलेशन सिंड्रोम' },
        type: 'neurological',
        causes: ['Stress', 'Anxiety', 'Fatigue', 'Caffeine intake'],
        riskFactors: ['History of anxiety', 'Sleep deprivation'],
        symptoms: ['Muscle twitching', 'Pins and needles', 'Fatigue'],
        progression: 'Non-progressive; usually fluctuates with stress levels.',
        diagnosticMarkers: ['Clinical evaluation', 'EMG to rule out other disorders'],
        prevention: 'Stress management, adequate sleep.',
        treatmentOptions: ['Anxiety management', 'Ensuring electrolyte balance'],
        requiresExpert: false
    },
    'sinusitis': {
        id: 'sinusitis',
        name: { en: 'Sinusitis (Sinus Infection)', hi: 'साइनुसाइटिस (साइनस संक्रमण)' },
        type: 'communicable',
        causes: ['Viral infection (most common)', 'Bacterial infection', 'Allergies', 'Nasal polyps'],
        riskFactors: ['Recent cold', 'Allergies', 'Smoking', 'Weakened immune system'],
        symptoms: ['Facial pain or pressure', 'Blocked nose', 'Thick yellow or green mucus', 'Reduced sense of smell', 'Headache'],
        progression: 'Acute sinusitis usually lasts 2-4 weeks; can become chronic if lasting more than 12 weeks.',
        diagnosticMarkers: ['Clinical examination', 'Nasal endoscopy', 'Imaging (CT scan) if chronic'],
        prevention: 'Hand washing, avoiding allergens, treating colds promptly.',
        treatmentOptions: ['Saline nasal irrigation', 'Nasal corticosteroids', 'Pain relievers', 'Antibiotics (if bacterial)'],
        requiresExpert: false
    },
    'allergic-rhinitis': {
        id: 'allergic-rhinitis',
        name: { en: 'Allergic Rhinitis (Hay Fever)', hi: 'एलर्जिक राइनाइटिस (हे फीवर)' },
        type: 'autoimmune',
        causes: ['Reaction to allergens like pollen, dust mites, or pet dander'],
        riskFactors: ['Family history of allergies or asthma', 'Exposure to allergens'],
        symptoms: ['Frequent sneezing', 'Runny or stuffy nose', 'Itchy, watery eyes', 'Itchy throat'],
        progression: 'Symptoms fluctuate with allergen exposure; can contribute to asthma or sinus issues.',
        diagnosticMarkers: ['Symptom history', 'Skin prick test', 'Specific IgE blood test'],
        prevention: 'Identifying and avoiding triggers, keeping windows closed during high pollen seasons.',
        treatmentOptions: ['Antihistamines', 'Nasal sprays', 'Decongestants', 'Immunotherapy'],
        requiresExpert: false
    }
};
